In [12]:
#1. hidden number:
import numpy as np
from IPython.display import display
arr1=np.arange(18,54)
display(arr1)
arr2=np.reshape(arr1,(6,-1))
display(arr2)
print(f"arr2[row=4][col=3]+17={arr2[3][2]+17}")

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53])

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53]])

arr2[row=4][col=3]+17=55


In [26]:
np.random.seed(42)
arr3=np.random.randint(1,100,(5,5))
print(arr3)
max_num=arr3.max()
print("max:",max_num)
print(f"max_num/2+7={max_num/2+7}")

[[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]
 [64 60 21 33 76]]
max: 93
max_num/2+7=53.5
